language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source --dev $COMPOSER_EXTRA_ARGS

script: phpunit --configuration phpunit.xml --coverage-text

after_script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
